AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - spec/fixtures/**

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
